{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # Site settings\
title: Mental Health in Tech\
description: A resource for understanding and improving mental health in the tech industry.\
baseurl: "" # the subpath of your site, e.g. /blog\
url: "" # the base hostname & protocol for your site, e.g. http://example.com\
repository: username/repo # GitHub username/repository\
\
# Build settings\
markdown: kramdown\
theme: minima\
plugins:\
  - jekyll-feed\
\
\
# Optional, for GitHub Pages: publish settings in the docs/ folder\
# destination: ./docs\
\
# SEO settings\
title: Mental Health in the Tech Industry\
description: A visual guide to mental health statistics and discussions within the US tech industry.\
\
}